# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=400)),
                ('location', models.CharField(max_length=400)),
                ('school', models.CharField(max_length=50)),
                ('Action', models.IntegerField(default=0)),
                ('Adventure', models.IntegerField(default=0)),
                ('Animation', models.IntegerField(default=0)),
                ('Biography', models.IntegerField(default=0)),
                ('Comedy', models.IntegerField(default=0)),
                ('Crime', models.IntegerField(default=0)),
                ('Documentary', models.IntegerField(default=0)),
                ('Drama', models.IntegerField(default=0)),
                ('Family', models.IntegerField(default=0)),
                ('Fantasy', models.IntegerField(default=0)),
                ('FilmNoir', models.IntegerField(default=0)),
                ('History', models.IntegerField(default=0)),
                ('Horror', models.IntegerField(default=0)),
                ('Music', models.IntegerField(default=0)),
                ('Musical', models.IntegerField(default=0)),
                ('Mystery', models.IntegerField(default=0)),
                ('Romance', models.IntegerField(default=0)),
                ('SciFi', models.IntegerField(default=0)),
                ('Sport', models.IntegerField(default=0)),
                ('Thriller', models.IntegerField(default=0)),
                ('War', models.IntegerField(default=0)),
                ('Western', models.IntegerField(default=0)),
            ],
        ),
    ]
