# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
