# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='time',
            field=models.CharField(default='', max_length=500),
        ),
    ]
