# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_action_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Comedy',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Documentary',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Fantasy',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FilmNoir',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Horror',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Musical',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Mystery',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Romance',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SciFi',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Thriller',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Western',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
