# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_adventure_animation_biography_comedy_crime_documentary_drama_family_fantasy_filmnoir_history_horror_'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
